version: '3'
# a service is nothing more than a container
# if you want more containers then create
# another "service"
services: 
  # Service named "api"
  api:
    build: .
    depends_on:
      - postgres
    ports: 
        # - <port on localhost>: <port on containers>
        - 8000:8000
    
    volumes:
      # Bind mount
      # updates/sync changes made in current directory
      # onto docker container
      - ./:/usr/src/app:ro
    
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    # env_file:
    #     - ./.env
    # Set env. variables. 
    # NOTE: env_file does the same thing    
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=AAaa11..
      - DATABASE_NAME=my_fastapi_database
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7 
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
  
  # service named "postgres"
  # this is our docker database
  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=AAaa11..
        - POSTGRES_DB=my_fastapi_database_docker
    # VOLUMES
    # Allows us to save data from our container onto our local
    # machine so that data persist even if with kill of a container
    # (data would be saved and use in a new container)
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
